### ISSUE TITLE
Top level array

### ISSUE THREAD

**Issue by benjamin-bergia** [jeganathgt/libjson-sh#1]
Hi, cool project.

I am using your library to generate some testing data and it has been working pretty well so far.
From what I can see, currently, the top level data structure is always an object.
It would be very nice to be able to use an array or an object.
We should also be able to call `json_add_array` without argument since an array doesn't have to be part of an object, we should be able to create an array of arrays such as `[[0, 1], [1, 0]]`.

**Comment by jeganathgt** [comment]
Thanks Bengamin,
I will fix the issue and update the git.
Please feel free to update more comments and issues.

**Comment by jeganathgt** [comment]
Hey Bengamin,
Your issue has been fixed and resolved.  You can mention the json type in json_init itself.

The below is the sample output from example/sample_2_1.sh
[ [ 20, 12.5 ], [ 40, 18.8 ] ]

Thanks for your support,
I am closing this issue now.

**Comment by benjamin-bergia** [comment]
Thanks
